# -*- coding: utf-8 -*-
"""Estadísticas de Calificaciones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dsFisPAmIEM2syidmi-mKmW9lEd1_WVE
"""

import pandas as pd

calificaciones_dt = pd.read_csv('calificaciones.csv')
calificaciones_dt.head()

promedio_por_materia = calificaciones_dt.groupby('Materia')['Calificación'].mean()
promedio_por_materia = promedio_por_materia.round(2)
print(promedio_por_materia)

promedio_por_estudiante = calificaciones_dt.groupby('Estudiante')['Calificación'].mean()
esudiante_con_promedio_mas_alto = promedio_por_estudiante.idxmax()
print("El estudiante con el mayor promedio es: ",esudiante_con_promedio_mas_alto)

promedio_por_estudiante = calificaciones_dt.groupby('Estudiante')['Calificación'].mean()
print(promedio_por_estudiante)

estudiantes_con_promedio_superior_a_85 = promedio_por_estudiante[promedio_por_estudiante > 85]
print(estudiantes_con_promedio_superior_a_85)

materia_con_mayor_cantidad_de_calificaciones = calificaciones_dt['Materia'].value_counts().idxmax()
print(materia_con_mayor_cantidad_de_calificaciones)

estudiantes_con_menor_promedio = promedio_por_estudiante.nsmallest(5)
print(estudiantes_con_menor_promedio)