# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TQ2_fHUzCtDFUKO8-2goHxdh2wbjXgc1
"""

import pandas as pd

clima_dt = pd.read_csv('clima.csv')
clima_dt.head()

temp_promedio = clima_dt.groupby('Ciudad')['Temperatura'].mean()
print(temp_promedio)

temperatura_maxima = clima_dt.loc[clima_dt['Temperatura'].idxmax()]
temperatura_minima = clima_dt.loc[clima_dt['Temperatura'].idxmin()]
print("Temperatura mas alta:\n", temperatura_maxima)
print("Temperatura mas baja:\n", temperatura_minima)

temp_cityMax = clima_dt.groupby('Ciudad')['Temperatura'].max()
temp_cityMin = clima_dt.groupby('Ciudad')['Temperatura'].min()
ciudad_Maxtemp = temp_cityMax.idxmax()
ciudad_Mintemp = temp_cityMin.idxmin()
print("Ciudad con la temperatura mas alta:", ciudad_Maxtemp)
print("Ciudad con la temperatura mas baja:", ciudad_Mintemp)

temp_Mayor = clima_dt[clima_dt['Temperatura'] > 30]
cantidad_Mayor = len(temp_Mayor)
print("Cantidad de registros con temperatura mayor a 30°C:", cantidad_Mayor)

dias_registrados = clima_dt.groupby('Ciudad')['Fecha'].count()
print(dias_registrados)